### ISSUE TITLE
6.006学习记录

### ISSUE THREAD

**Issue by forrestchang** [forrestchang/6.006#1]
记录下学习6.006的任务进度。

**Comment by forrestchang** [comment]
- [x] Lecture 1 Video
- [ ] Rewrite Lecture 1 notes

**Comment by Bayesky** [comment]
打印版的太贵了，这个书多少页呢？我找了一家不错的打印社，这本书要130.....

**Comment by forrestchang** [comment]
@Bayesky 1000+页，我打印就是130+￥，原版800+￥，实在不行可以看电子版的。

**Comment by forrestchang** [comment]
### Lecture 2 - Models of Computation, Document Distance
- [ ] Watch Lecture 1 Video

**Comment by Bayesky** [comment]
感觉怎样了？

**Comment by Bayesky** [comment]
好想你删掉了一条评论 我都没来得及看是什么

**Comment by forrestchang** [comment]
@Bayesky 最近在复习期末考试，另外在刷CS61A这门课（补补Python的知识），所以进度不是很快。删掉的那条评论忘记是写的什么了。。。。

**Comment by Bayesky** [comment]
这个Python是3.5的还是2.7的？
